/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Standard I/O configuration */
export const enum StdioConfigJs {
  /** Inherit from parent process */
  Inherit = 'Inherit',
  /** Create a new pipe */
  Piped = 'Piped',
  /** Redirect to null */
  Null = 'Null'
}
/** Process exit status */
export interface ExitStatusJs {
  success: boolean
  code?: number
}
/** Process output with stdout and stderr */
export interface ProcessOutputJs {
  status: ExitStatusJs
  stdout: Buffer
  stderr: Buffer
}
/** Resource limits for sandboxed processes */
export interface ResourceLimitsJs {
  /** Maximum memory in bytes */
  maxMemoryBytes?: number
  /** Maximum CPU time in seconds */
  maxCpuTimeSecs?: number
  /** Maximum file size in bytes */
  maxFileSizeBytes?: number
  /** Maximum number of processes */
  maxProcesses?: number
}
/** Main sandbox configuration from JavaScript */
export interface SandboxConfigJs {
  /** Network policy configuration */
  network?: NetworkPolicyConfig
  /** Security configuration */
  security?: SecurityConfigJs
  /** Paths with write access */
  writablePaths?: Array<string>
  /** Paths with read-only access */
  readablePaths?: Array<string>
  /** Paths with execute access */
  executablePaths?: Array<string>
  /** Python configuration */
  python?: PythonConfigJs
  /** Working directory path */
  workingDir?: string
  /** Environment variables to pass through */
  envPassthrough?: Array<string>
  /** Resource limits */
  limits?: ResourceLimitsJs
}
/** Get strict sandbox preset configuration */
export declare function presetStrict(): SandboxConfigJs
/** Get Python dev sandbox preset configuration */
export declare function presetPythonDev(): SandboxConfigJs
/** Get Python data science sandbox preset configuration */
export declare function presetPythonDataScience(): SandboxConfigJs
/** Helper to create an IPC router (factory function for cleaner API) */
export declare function createIpcRouter(): IpcRouterJs
/** Domain request information exposed to JavaScript */
export interface DomainRequestJs {
  target: string
  port: number
  direction: string
  pid: number
}
/** Network policy configuration from JavaScript */
export interface NetworkPolicyConfig {
  /** Policy type: "deny-all", "allow-all", or "allow-list" */
  policyType: string
  /** Domains for allow-list policy (supports wildcards like "*.example.com") */
  domains?: Array<string>
}
/** Virtual environment configuration */
export interface VenvConfigJs {
  /** Path to the virtual environment */
  path?: string
  /** Python interpreter path */
  python?: string
  /** Packages to install */
  packages?: Array<string>
  /** Include system site-packages */
  systemSitePackages?: boolean
  /** Use uv package manager */
  useUv?: boolean
}
/** Python sandbox configuration */
export interface PythonConfigJs {
  /** Virtual environment configuration */
  venv?: VenvConfigJs
  /** Allow pip install in sandbox */
  allowPipInstall?: boolean
}
/**
 * Create a new sandbox with optional configuration
 *
 * This is the main entry point for creating sandboxes.
 *
 * @example
 * ```typescript
 * import { createSandbox } from 'leash-sandbox';
 *
 * const sandbox = await createSandbox();
 * const output = await sandbox.command('echo').arg('hello').output();
 * console.log(output.stdout.toString()); // "hello
"
 * ```
 */
export declare function createSandbox(config?: SandboxConfigJs | undefined | null): Promise<Sandbox>
/** Security configuration for the sandbox */
export interface SecurityConfigJs {
  /** Protect user home directories (/Users, /home) */
  protectUserHome?: boolean
  /** Protect SSH/GPG credentials (.ssh, .gnupg) */
  protectCredentials?: boolean
  /** Protect cloud provider config (.aws, .kube, .docker) */
  protectCloudConfig?: boolean
  /** Protect browser data (cookies, history, passwords) */
  protectBrowserData?: boolean
  /** Protect system keychain */
  protectKeychain?: boolean
  /** Protect shell history (.bash_history, .zsh_history, etc.) */
  protectShellHistory?: boolean
  /** Protect package manager credentials (.npmrc, .pypirc, .netrc) */
  protectPackageCredentials?: boolean
  /** Allow GPU access (Metal, CUDA, OpenCL) */
  allowGpu?: boolean
  /** Allow NPU/Neural Engine access (CoreML, ANE) */
  allowNpu?: boolean
  /** Allow general hardware access (USB, Bluetooth, cameras) */
  allowHardware?: boolean
}
/** Get strict security preset */
export declare function securityConfigStrict(): SecurityConfigJs
/** Get permissive security preset */
export declare function securityConfigPermissive(): SecurityConfigJs
/** A spawned child process in the sandbox */
export declare class ChildProcessJs {
  /** Get the process ID */
  get pid(): number
  /** Wait for the process to exit */
  wait(): Promise<ExitStatusJs>
  /** Wait for the process to exit and collect all output */
  waitWithOutput(): Promise<ProcessOutputJs>
  /** Kill the process */
  kill(): Promise<void>
  /** Check if the process has exited without blocking */
  tryWait(): Promise<ExitStatusJs | null>
  /** Write data to the process stdin */
  writeStdin(data: Buffer): Promise<void>
  /** Read available data from stdout (non-blocking) */
  readStdout(maxBytes: number): Promise<Buffer>
  /** Read available data from stderr (non-blocking) */
  readStderr(maxBytes: number): Promise<Buffer>
}
/** Command builder for executing programs in the sandbox */
export declare class Command {
  /** Add a single argument */
  arg(value: string): this
  /** Add multiple arguments */
  args(values: Array<string>): this
  /** Set an environment variable */
  env(key: string, value: string): this
  /** Set multiple environment variables */
  envs(vars: Array<Array<string>>): this
  /** Set the working directory */
  cwd(dir: string): this
  /** Configure stdin */
  stdin(config: StdioConfigJs): this
  /** Configure stdout */
  stdout(config: StdioConfigJs): this
  /** Configure stderr */
  stderr(config: StdioConfigJs): this
  /** Run the command and collect all output */
  output(): Promise<ProcessOutputJs>
  /** Run the command and return only exit status */
  status(): Promise<ExitStatusJs>
  /** Spawn the command as a child process */
  spawn(): Promise<ChildProcessJs>
}
/**
 * IPC router for handling commands from sandboxed processes
 *
 * Note: IPC support in the Node.js binding is currently limited.
 * For full IPC functionality, use the Rust library directly.
 */
export declare class IpcRouterJs {
  /** Create a new empty IPC router */
  constructor()
  /** Get the list of registered method names */
  methods(): Array<string>
}
/**
 * A sandbox for running untrusted code with restricted permissions
 *
 * All network traffic from sandboxed processes is routed through a local proxy
 * that applies the configured network policy for filtering.
 *
 * When disposed, the sandbox will:
 * - Stop the network proxy
 * - Stop the IPC server (if enabled)
 * - Kill all child processes that were spawned within it
 * - Delete the working directory (unless `keepWorkingDir()` was called)
 */
export declare class Sandbox {
  /** Create a new sandbox with optional configuration */
  static create(config?: SandboxConfigJs | undefined | null): Promise<Sandbox>
  /** Get the working directory path */
  get workingDir(): string
  /** Get the proxy URL for environment variables */
  get proxyUrl(): string
  /** Create a command builder for running a program in the sandbox */
  command(program: string): Command
  /** Run a Python script in the sandbox */
  runPython(script: string): Promise<ProcessOutputJs>
  /** Keep the working directory after the sandbox is disposed */
  keepWorkingDir(): Promise<void>
  /**
   * Dispose the sandbox (called automatically, but can be called manually)
   *
   * This will:
   * - Stop the network proxy
   * - Kill all child processes
   * - Delete the working directory (unless keepWorkingDir was called)
   */
  dispose(): Promise<void>
}
